#!/usr/bin/env python3
"""Interactive local .env setup. Never commits secrets — writes gitignored .env only."""

from __future__ import annotations

import getpass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV = ROOT / ".env"
EXAMPLE = ROOT / ".env.example"

FIELDS = [
    ("CA_API_URL", "CriticalAsset API URL", False),
    ("CA_CLIENT_ID", "CriticalAsset M2M Client ID (from credential sheet)", False),
    ("CA_CLIENT_SECRET", "CriticalAsset M2M Client Secret", True),
    ("CA_CONSOLE_EMAIL", "Console email (human login fallback)", False),
    ("CA_CONSOLE_PASSWORD", "Console password", True),
    ("OPENAI_API_KEY", "OpenAI API key (for AI structuring screenshots)", True),
    ("OPENAI_MODEL", "OpenAI model", False),
]


def load_existing() -> dict[str, str]:
    if not ENV.exists():
        return {}
    out: dict[str, str] = {}
    for line in ENV.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        out[key.strip()] = val.strip()
    return out


def main() -> int:
    print("Team 12 — local .env setup")
    print("Secrets stay on this machine only (.env is gitignored).\n")
    print("Do NOT paste API keys into GitHub, GitHub Pages, or the browser.\n")

    existing = load_existing()
    if not existing and EXAMPLE.exists():
        existing = {}
        for line in EXAMPLE.read_text().splitlines():
            if "=" in line and not line.strip().startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()

    lines = ["# Team 12 local secrets — generated by scripts/setup_env.py", ""]
    for key, label, secret in FIELDS:
        current = existing.get(key, "")
        hint = f" [{current[:8]}…]" if current and secret and len(current) > 8 else (f" [{current}]" if current and not secret else "")
        prompt = f"{label}{hint} (Enter to keep, or type new value): "
        if secret:
            val = getpass.getpass(prompt)
        else:
            val = input(prompt).strip()
        if not val:
            val = current
        lines.append(f"{key}={val}")

    ENV.write_text("\n".join(lines) + "\n")
    print(f"\nWrote {ENV}")
    print("Next: python3 scripts/auth.py && python3 backend/api_server.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
